// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOXQUy5vfMRKAyGuGU6qXUyaa6V1A4bX8',
    appId: '1:74431047594:web:7853865d432535fee1edd3',
    messagingSenderId: '74431047594',
    projectId: 'task-d9a5e',
    authDomain: 'task-d9a5e.firebaseapp.com',
    storageBucket: 'task-d9a5e.appspot.com',
    measurementId: 'G-ZLMRDV74B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwdjXIFGLNVw8oN5ARr_2nKSkXFnIc3Wk',
    appId: '1:74431047594:android:d0fcd323d9e1d0cee1edd3',
    messagingSenderId: '74431047594',
    projectId: 'task-d9a5e',
    storageBucket: 'task-d9a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnHaKQPqvN0vyWzSk0QhWzplUe01LHlrU',
    appId: '1:74431047594:ios:f0cc2c5e54b42ad6e1edd3',
    messagingSenderId: '74431047594',
    projectId: 'task-d9a5e',
    storageBucket: 'task-d9a5e.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnHaKQPqvN0vyWzSk0QhWzplUe01LHlrU',
    appId: '1:74431047594:ios:f0cc2c5e54b42ad6e1edd3',
    messagingSenderId: '74431047594',
    projectId: 'task-d9a5e',
    storageBucket: 'task-d9a5e.appspot.com',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOXQUy5vfMRKAyGuGU6qXUyaa6V1A4bX8',
    appId: '1:74431047594:web:0484f5f544265adee1edd3',
    messagingSenderId: '74431047594',
    projectId: 'task-d9a5e',
    authDomain: 'task-d9a5e.firebaseapp.com',
    storageBucket: 'task-d9a5e.appspot.com',
    measurementId: 'G-LVN32KNBFJ',
  );
}
